github.com:
    users:
        BrunoCiccarino:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: BrunoCiccarino
